#!/usr/bin/env python

# copyright (c) christopher@frenning.com 2020
# license: the unlicense, see https://unlicense.org
# usage: getsetting.py <setting>
# reads configuration.toml file and returns the value of the setting

import os
import sys
import toml

try:
    configuration_file_name = os.path.dirname(os.path.abspath(__file__)) + "/configuration.toml"
    configuration = toml.load(configuration_file_name)

    if ( len(sys.argv) < 2 ):
        print("Specify setting to load as an argument to this process")
        exit(1)
    else:
        try:
            val = configuration[sys.argv[1]]
        except:
            print("Setting not found in " + configuration_file_name)
            exit(3)

        print(val)
        exit(0)
except Exception as ex:
    print(ex.message)
    exit(2)