name: Deploy ingestion to Azure

env:
  AZURE_WEBAPP_NAME: vkrjjzaur

on:
  push:
    branches: [ "main" ]
    paths: [ "workers/ingestion/**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.ACR_FQDN }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Where are we
        run: pwd
                
      - name: Move into server directory
        run: cd ./workers/ingestion
        
      - name: What is here
        run: ls

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          tags: ${{ secrets.ACR_FQDN }}/zephyr-ingestion:latest # ${{ env.REPO }}:${{ github.sha }}
          file: ./workers/ingestion/Dockerfile
          context: ./workers/ingestion
          push: true